version: '3'

services:
  client:
    container_name: "client-app-arif"
    build: ./client-server/.
    ports:
      - '3000:3000'
    networks:
      - Arifnetwork
    depends_on:
      - redis
      - db
      - api-server
      - worker-server
    volumes:
      - ./client-server:/app2
  api-server:
    container_name: "api-server-arif"
    build: ./api-server/.
    environment:
      - PORT=5001
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TABLE=${MYSQL_TABLE}
    ports:
      - '5001:5001'
    networks:
      - Arifnetwork
    depends_on:
      - db
      - redis
      - worker-server
    volumes:
      - ./api-server:/app

  worker-server:
    container_name: "worker-server-arif"
    build: ./worker-server/.
    environment:
      - PORT=5002
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TABLE=${MYSQL_TABLE}
    networks:
      - Arifnetwork
    depends_on:
      - db
      - redis
    volumes:
      - ./worker-server:/app
  db:
    container_name: "mysql-db-arif"
    build: ./db-server/.
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # ports:
    #   - '3306:3306'
    networks:
      - Arifnetwork
    volumes:
      - ./db-server:/app
  redis:
    container_name: "redis-service-arif"
    image: "redis:latest"
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass mypassword
    # ports:
    #   - '6379:6379'
    networks:
      - Arifnetwork
    # volumes:
    #   - ${PWD}:/app

networks:
  Arifnetwork:
    driver: bridge
